<?php 
$template = file_get_contents('templates/main.tpl'); 
$template = str_replace('{HEADER_TITLE}', 'LR3', $template);
$template = str_replace('{MAIN_MENU}', file_get_contents('templates/main_menu.tpl'), $template);
$template = str_replace('{CONTENT}', file_get_contents('templates/content.tpl'), $template);
$template = str_replace('{NEWS}', file_get_contents('templates/news.tpl'), $template);
$template = str_replace('{FOOTER}', file_get_contents('templates/footer.tpl'), $template);
$myfile = fopen("site.cfg", "r");
	$main_color = str_replace("main_color = ", "bgcolor=", fgets($myfile));
	$copyright_color = str_replace("copyright_color = ", "bgcolor=", fgets($myfile));
fclose($myfile);
$main_color =  substr($main_color, 3);
	$template = str_replace('{main_color}', $main_color, $template);
	$template = str_replace('{copyright_color}', $copyright_color, $template);
	$template = str_replace('{TODAY_D}', date("j"), $template);
	$template = str_replace('{TODAY_M}', date("n"), $template);
	$template = str_replace('{TODAY_Y}', date("Y"), $template);
	$template = str_replace('{NOW_H}', date("G"), $template);
	$template = str_replace('{NOW_M}', date("i"), $template);
	$template = str_replace('{NOW_S}', date("s"), $template);
echo $template;